menu:
- {name: 'research', url: '/research'}
- {name: 'publications', url: '/publications'}
- {name: 'software', url: '/software'}
- {name: 'people', url: '/people'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Chris', title: 'Postdoctoral Associate', department: 'Cooperative Institute for Research in Environmental Sciences', institution: 'University of Colorado Boulder', institution_address: 'Boulder, CO', email: 'chriscs at colorado dot edu', image: 'assets/img/headshot.jpg', url: 'me'}
#- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
#- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

# courses:
# - {name: 'Vector Calculus', url: 'vector-calculus'}
# - {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
# - {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/chriscrsmith'}
#- {icon: 'twitter', link: 'https://twitter.com/chriscrsmith'}
#- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Chris Smith', title: 'Assistant Professor', department: 'Department of Biology', institution: 'Indiana University Bloomington', institution_address: 'Bloomington, IN', email: 'chriscs at iu dot edu'}
